# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_thingdoer_wrappers", use_symbols = TRUE, package_name = "thingdoer")

#' @usage NULL
#' @useDynLib thingdoer, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' solves the exercise given the path to a valid sql database containing the annotated genomic data.
#' @export
do_the_thing <- function(path) .Call(wrap__do_the_thing, path)


# nolint end
