# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_thingdoer_wrappers", use_symbols = TRUE, package_name = "thingdoer")

#' @usage NULL
#' @useDynLib thingdoer, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' add to nums
#' @export
add <- function(x, y) .Call(wrap__add, x, y)

#' does the thing
#' @export
do_the_thing <- function() .Call(wrap__do_the_thing)


# nolint end
